services:
  postgres:
    image: postgres:alpine
    ports: 
      - 5432:5432
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev

  atlas:
    image: arigaio/atlas:latest-alpine
    depends_on:
      - postgres
    profiles:
      - atlas
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      DEV_DATABASE_URL: postgresql://postgres:postgres@postgres:5432/dev?sslmode=disable
    volumes:
      - ./atlas.hcl:/db/atlas.hcl:ro
      - ./schema.sql:/db/schema.sql:ro
      - ./migrations:/db/migrations
    working_dir: /db
